# Should throw exception

def main(x):
    y = x + 1