# Should throw exception

def main(x):
    return x>>1